name: test
on:
  workflow_dispatch:
jobs:
  Stage_1:
    name: Stage 1
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Running Stage 1
  Stage_2:
    name: Stage 2
    runs-on: ubuntu-latest
    needs: Stage_1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Running Stage 2
  Stage_3:
    name: Stage 3
    runs-on: ubuntu-latest
    needs: Stage_2
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Running Stage 3
  Stage_4:
    name: Stage 4
    runs-on: ubuntu-latest
    needs: Stage_3
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Running Stage 4
  Stage_5:
    name: Stage 5
    runs-on: ubuntu-latest
    needs: Stage_4
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Running Stage 5
